{% set version = "2.1.11" %}

package:
  name: libmixmod
  version: {{ version }}

source:
  url: https://github.com/mixmod/mixmod/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e95414decf5b2c2c5eebd7fca10e0100f2d753cbfca0694f4ac75da3b39b005e
  patches:
    # https://github.com/mixmod/mixmod/pull/31
    - 0001-Random-Use-c-11-apis-instead-of-clock_gettime.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libmixmod', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - eigen

test:
  commands:
    - test -f ${PREFIX}/include/mixmod.h  # [unix]
    - test -f ${PREFIX}/lib/libmixmod${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\mixmod.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\mixmod.lib exit 1  # [win]

about:
  home: https://github.com/mixmod/mixmod
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: UTIL/gpl.txt
  summary: Supervised, Unsupervised, Semi-Supervised Classification with MIXture MODelling

extra:
  recipe-maintainers:
    - jschueller
