context:
  version: "2.1.12"

package:
  name: libmixmod
  version: ${{ version }}

source:
  url: https://github.com/mixmod/mixmod/archive/refs/tags/v${{ version }}.tar.gz
  sha256: dd6c0d1fef7f2aa80e0c77680baa0718aa6326302bfd11b7e5dd99a378e5b277

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - if: osx
      then: llvm-openmp
    - if: linux
      then: libgomp
  host:
    - eigen
  run_exports:
    - ${{ pin_subpackage('libmixmod', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - mixmod.h
      lib:
        - if: unix
          then: mixmod

about:
  homepage: https://github.com/mixmod/mixmod
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: UTIL/gpl.txt
  summary: Supervised, Unsupervised, Semi-Supervised Classification with MIXture MODelling

extra:
  recipe-maintainers:
    - jschueller
